name: Deploy to Firebase Hosting on push

on:
  push:
    branches:
      - main # This runs on every push to the "main" branch. Modify the branch name if needed.

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx for multi-stage build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # # Step 3: Log in to DockerHub (if necessary, otherwise skip)
      # - name: Log in to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image with multi-stage builds
      - name: Build Docker image
        run: |
          docker build --target production -t my-nestjs-app:latest .

      # Step 5: Run the production Docker image
      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 my-nestjs-app:latest
