name: Deploy to Firebase Hosting on push

on:
  push:
    branches:
      - main # This runs on every push to the "main" branch. Modify the branch name if needed.

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production
      PORT: ${{ secrets.PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_SSL: ${{ secrets.DB_SSL }}
      PGADMIN_EMAIL: ${{ secrets.PGADMIN_EMAIL }}
      PGADMIN_PASSWORD: ${{ secrets.PGADMIN_PASSWORD }}

      JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
      JWT_FORGET_PASSWORD_SECRET: ${{ secrets.JWT_FORGET_PASSWORD_SECRET }}

      # Minio
      MINIO_END_POINT: ${{ secrets.MINIO_END_POINT }}
      MINIO_PORT: ${{ secrets.MINIO_PORT }}
      MINIO_IS_USE_SSL: ${{ secrets.MINIO_IS_USE_SSL }}
      MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
      MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      BUCKET_REGION: ${{ secrets.BUCKET_REGION }}

      MAIL_LOGIN: ${{ secrets.MAIL_LOGIN }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}

      SALT_VALUE: ${{ secrets.SALT_VALUE }}
      REDIS_URL: ${{ secrets.REDIS_URL }}

      APP_ID_ONESIGNAL: ${{ secrets.APP_ID_ONESIGNAL }}
      API_KEY_ONESIGNAL: ${{ secrets.API_KEY_ONESIGNAL }}

      RP_NAME: ${{ secrets.RP_NAME }}
      RP_ID: ${{ secrets.RP_ID }}
      ORIGIN: ${{ secrets.ORIGIN }}
      THROTTLE_TTL: ${{ secrets.THROTTLE_TTL }}
      THROTTLE_LIMIT: ${{ secrets.THROTTLE_LIMIT }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install NestJS CLI globally
        run: npm install -g @nestjs/cli
      - run: npm ci

      - name: project_a build
        run: nest build

      # - name: Install dependencies
      #   run: npm install

      # - name: Build the project for production
      #   run: npm run build

      # - name: Start the project
      #   run: node dist/main.js  # Ensure this matches the entry point of your built app

      # - name: Start the project in production mode
      #   run: npm run start:dev:dist
