name: Deploy to Firebase Hosting on push

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT }}
          service_account_key: ${{ secrets.GCLOUD_KEY }}
          export_default_credentials: true

      # Step 3: Configure Docker to use gcloud
      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/playground-105d9/nestjs-app:latest .

      # Step 5: Push Docker image to Artifact Registry
      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/playground-105d9/nestjs-app:latest

      # Step 6: Deploy to Google Cloud Run
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy nestjs-app \
            --image us-central1-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/playground-105d9/nestjs-app:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 8080