name: Deploy to Firebase Hosting on push

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production
      PORT: ${{ secrets.PORT }}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install NestJS CLI
      - name: Install NestJS CLI
        run: npm install -g @nestjs/cli

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      # Step 6: Add Dockerfile steps to use the Node.js image and expose the port
      - name: Use Node.js Docker image
        run: |
          echo -e "FROM --platform=linux/amd64 node:16-alpine\n\nEXPOSE 8080" > Dockerfile

      # Step 7: Run the app (optional for local validation)
      - name: Run the app (optional)
        run: npm run start:prod &
