name: Deploy to Firebase Hosting on push

on:
  push:
    branches:
      - main # This runs on every push to the "main" branch. Modify the branch name if needed.

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production
      PORT: ${{ secrets.PORT }}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the NestJS app for production
      - name: Build the app
        run: npm run build

      # Step 5: Run the app (optional for local validation)
      - name: Run the app (optional)
        run: npm run start:prod &
        # The `&` allows the server to run in the background (optional if you just want to validate)
