name: Deploy to Firebase Hosting on push

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production
      PORT: ${{ secrets.PORT }} # Ensure this secret is set in your GitHub repository settings

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker buildx build --platform linux/amd64 -t gcr.io/${{ secrets.GCLOUD_PROJECT }}/nestjs-app .

      # Step 4: Push Docker image to Google Container Registry
      - name: Push Docker image
        run: docker push gcr.io/${{ secrets.GCLOUD_PROJECT }}/nestjs-app

      # Step 5: Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --project ${{ secrets.GCLOUD_PROJECT }} --token ${{ secrets.FIREBASE_TOKEN }}