name: Deploy to Firebase Hosting on push

on:
  push:
    branches:
      - main

name: Deploy to Firebase Hosting on push

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCLOUD_KEY }}
          project_id: ${{ secrets.GCLOUD_PROJECT }}

      # Step 3: Authenticate Docker with Google Container Registry
      - name: Configure Docker for GCR
        run: gcloud auth configure-docker gcr.io

      # - name: Authenticate to Google Cloud
      #   run: echo "${{ secrets.GCLOUD_KEY }}" | base64 --decode > $HOME/gcloud-key.json

      # Step 4: Build and tag Docker image
      - name: Build Docker image
        run: docker build -t gcr.io/${{ secrets.GCLOUD_PROJECT }}/nestjs-app .

      # Step 5: Push Docker image to Google Container Registry
      - name: Push Docker image
        run: docker push gcr.io/${{ secrets.GCLOUD_PROJECT }}/nestjs-app

      # Step 6: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy nestjs-app \
            --image gcr.io/${{ secrets.GCLOUD_PROJECT }}/nestjs-app \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 8080